FROM python:3.7-slim
RUN apt-get update && apt-get install -y gcc curl wget
RUN apt-get install -y npm && npm install nodemon --global
WORKDIR /stallone-service
ENV PYTHONPATH /stallone-service
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY . /stallone-service
#CMD ["python", "main.py"]