version: '3'

services:

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

    networks:
      - network


  trade-receiver-service:
    build:
      context: trade-receiver-service/
      dockerfile: DockerFile
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    tty: true
    networks:
      - network


  market-data-service:
    build:
      context: market-data-service/
      dockerfile: Dockerfile
    environment:
      AMQP_URL: 'amqp://rabbitmq?connection_attempts=5&retry_delay=5'
    tty: true
    networks:
      - network

networks:
  network: {}