FROM python:3.7-slim
RUN apt-get update && apt-get install -y gcc curl wget
RUN apt-get install -y npm && npm install nodemon --global
WORKDIR /risk_publisher
ENV PYTHONPATH "${PYTHONPATH}:/risk_publisher:/risk_publisher/common_utils"
COPY ./risk_publisher/requirements.txt requirements.txt
RUN pip install -r requirements.txt
COPY ./risk_publisher/ /risk_publisher
COPY ./common_utils/ /risk_publisher/common_utils
